# Generated by Django 5.2 on 2025-04-29 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('located_at', models.CharField(max_length=255)),
                ('total_crates', models.IntegerField()),
                ('filled_crates', models.IntegerField()),
                ('empty_crates', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('damage_crates', models.IntegerField()),
                ('missing_crates', models.IntegerField()),
                ('container_crates', models.IntegerField()),
                ('ready_to_sell_crates', models.IntegerField()),
                ('operation_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
