# Generated by Django 5.2 on 2025-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0004_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_MAINTENANCE', 'Under Maintenance')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('total_crates', models.IntegerField()),
                ('filled_crates', models.IntegerField()),
                ('empty_crates', models.IntegerField()),
            ],
        ),
    ]
