# Generated by Django 5.2 on 2025-04-29 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0007_loadoutbunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('crates', models.IntegerField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='PENDING', max_length=50)),
                ('unload_at', models.DateTimeField(blank=True, null=True)),
                ('sg_exit_at', models.DateTimeField(blank=True, null=True)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crates.collectioncenter')),
                ('loadout_bunch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crates.loadoutbunch')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crates.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
