# Generated by Django 5.2 on 2025-04-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0010_alter_collectioncenter_floor_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='total_crates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
