# Generated by Django 5.2 on 2025-04-30 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0012_warehouse_warehouse_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='security_gate_keeper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_gate_keeper_warehouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
