# Generated by Django 5.2 on 2025-04-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0013_warehouse_security_gate_keeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadout',
            old_name='loadout_bunch_id',
            new_name='loadout_bunch',
        ),
        migrations.RenameField(
            model_name='loadoutbunch',
            old_name='truck_id',
            new_name='truck',
        ),
    ]
