# Generated by Django 5.2 on 2025-05-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0014_rename_loadout_bunch_id_loadout_loadout_bunch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadout',
            old_name='verified_at',
            new_name='entryCheck_at',
        ),
    ]
