# Generated by Django 5.2 on 2025-05-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0015_rename_verified_at_loadout_entrycheck_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadout',
            name='sg_exit_at',
        ),
        migrations.AddField(
            model_name='loadoutbunch',
            name='sg_exit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
