# Generated by Django 5.2 on 2025-05-02 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('crates', '0016_remove_loadout_sg_exit_at_loadoutbunch_sg_exit_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CratesManagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_location_object_id', models.PositiveIntegerField()),
                ('to_location_object_id', models.PositiveIntegerField()),
                ('total_crates', models.IntegerField()),
                ('filled_crates', models.IntegerField()),
                ('empty_crates', models.IntegerField()),
                ('missing_crates', models.IntegerField()),
                ('damaged_crates', models.IntegerField()),
                ('from_location_content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'crates'), ('model__in', ['warehouse', 'collectioncenter'])), on_delete=django.db.models.deletion.CASCADE, related_name='from_location_logs', to='contenttypes.contenttype')),
                ('loadout_bunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crates.loadoutbunch')),
                ('to_location_content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'crates'), ('model__in', ['warehouse', 'collectioncenter'])), on_delete=django.db.models.deletion.CASCADE, related_name='to_location_logs', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
