# Generated by Django 5.2 on 2025-05-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0017_cratesmanagementlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cratesmanagementlog',
            name='damaged_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cratesmanagementlog',
            name='empty_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cratesmanagementlog',
            name='filled_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cratesmanagementlog',
            name='missing_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cratesmanagementlog',
            name='total_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
