# Generated by Django 5.2 on 2025-05-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0018_alter_cratesmanagementlog_damaged_crates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadout',
            name='sg_exit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
