# Generated by Django 5.2 on 2025-05-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0020_remove_loadout_status_loadout_entrycheck_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cratesmanagementlog',
            name='loadout_bunch',
        ),
        migrations.AddField(
            model_name='cratesmanagementlog',
            name='loadout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cratesmanagementlog_loadout', to='crates.loadout'),
        ),
    ]
