# Generated by Django 5.2 on 2025-05-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0021_remove_cratesmanagementlog_loadout_bunch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cratesmanagementlog',
            name='loadout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cratesmanagementlog_loadout', to='crates.loadout'),
        ),
    ]
