# Generated by Django 5.2 on 2025-05-06 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0022_alter_cratesmanagementlog_loadout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadout',
            name='loadout_bunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadout_loadoutbunch', to='crates.loadoutbunch'),
        ),
    ]
