# Generated by Django 5.2 on 2025-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0023_alter_loadout_loadout_bunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadoutbunch',
            name='loadoutBunch_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
