# Generated by Django 5.2 on 2025-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0024_loadoutbunch_loadoutbunch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadoutbunch',
            name='crates',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loadout',
            name='crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='empty_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='filled_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='total_crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
