# Generated by Django 5.2 on 2025-05-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0025_loadoutbunch_crates_alter_loadout_crates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadoutbunch',
            name='loadoutBunch_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOADED', 'Loaded'), ('APPROVED', 'Approved'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
