# Generated by Django 5.2 on 2025-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0026_alter_loadoutbunch_loadoutbunch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadout',
            name='truck_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('GOING', 'Going'), ('ENTRY_CHECKED', 'Entry Checked'), ('UNLOADED', 'Unloaded'), ('EXITED', 'Exited')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='loadoutbunch',
            name='crates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
