# Generated by Django 5.2 on 2025-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0027_alter_loadout_truck_status_alter_loadoutbunch_crates'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadoutbunch',
            name='load_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
