# Generated by Django 5.2 on 2025-05-08 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crates', '0028_loadoutbunch_load_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInEmptyCrates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_description', models.TextField(blank=True, null=True)),
                ('crates', models.IntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crates.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
